Adds support for ANGLE_InstancedArrays extension
cedricpinson/osgjs pull request #968
Opened 2018-04-02 10:21 UTC by jtorresfabra

Also executed a grunt prettier on the codebase

2018-04-06 14:11 UTC, cedricpinson commented
could you splits commits about prettier and the real changes plz ?

2018-04-13 09:24 UTC, jtorresfabra commented on sources/osg/Geometry.js
> +            if (this._instancedArrayMap === undefined) this._instancedArrayMap = new window.Map();
Maybe better to use a {}?

2018-04-13 09:25 UTC, jtorresfabra commented
@cedricpinson done

2018-04-17 14:56 UTC, Kuranes commented on sources/osgDB/readerParser.js
> +                var count = primitives[p].count || primitives[p]._count;
same ?

2018-04-17 14:58 UTC, Kuranes commented on sources/osg/Node.js
> +    this._computeBoundingSphereCallback = undefined;
_computeBoundingSphereCallback never used ?
need to remove it

2018-04-17 15:05 UTC, Kuranes requested changes
- inconsistency between primitives member names (with or without '_') and accessor usage (getIndices())
- doesn't work in webgl2
- Why we do not use the current mechanism in webglcaps to create a backport of webgl2 "gl.DrawElementInstanced, gl.DrawArrayInstanced" to webgl1 ? ( see https://github.com/cedricpinson/osgjs/blob/master/sources/osg/WebGLCaps.js#L365-L383 && https://developer.mozilla.org/en-US/docs/Web/API/ANGLE_instanced_arrays for webgl2 names)

Would give Clearer code and would work on webgl1/2 (and allow to remove the "ANGLE" text from everywhere for just "instanced")

2019-10-18 12:29 UTC, closed without merging